Dev
ChugunovaMarja/TAT pull request #1
Opened 2016-10-02 21:18 UTC by ChugunovaMarja

2016-10-02 21:21 UTC, ChugunovaMarja commented
Pulled

2016-10-02 21:41 UTC, ChugunovaMarja commented
Исправила по отступам что могла, но уже, похоже, извращаться начинаю. Если все еще не то, завтра стандарты перечитаю еще раз

2016-10-03 07:06 UTC, AlexanderSoroka requested changes

2016-10-03 07:06 UTC, AlexanderSoroka commented on Calculator.java
> +/** main class for calculating sum,
It must start from new line:
/**
 \* main class

2016-10-03 07:06 UTC, AlexanderSoroka commented on Calculator.java
> +} else
Missed {} after else

2016-10-03 07:06 UTC, AlexanderSoroka commented on Calculator.java
>  public static double sum(double a, double b) { //calculates sum of two numbers
Comments for method must be in javadoc

2016-10-03 07:06 UTC, AlexanderSoroka commented on PrintHelloName.java
> +    if (args.length > 0)
Missed {} after if and else

2016-10-03 08:10 UTC, closed without merging